config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:session, :password, :registration], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "(:locale)", locale: /en|pl/ do
    devise_for :users, skip: [:omniauth_callbacks]
    ActiveAdmin.routes(self)
    get 'search' => 'videos#index', as: :search

    root 'home#index'

    get 'set_language/en', as: :en
    get 'set_language/pl', as: :pl

    scope '/lighter' do
      get '/construction' => 'lighter#construction', as: :construction
      get '/types' => 'lighter#types', as: :types
      get '/history' => 'lighter#history', as: :history
    end

    resources :tutorials
    resources :entries
    resources :images
    resources :comments

    resources :videos do
      member do
        post :vote
        post :add_comment
        get :tags
      end
    end
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  mount_uploader :source, VideoUploader
  acts_as_taggable
  acts_as_commentable
  paginates_per 12
  belongs_to :user
  validates :title, :kind, presence: true
  validates_numericality_of :kind, less_than_or_equal_to: 2, greater_than: 0, message: 'must be specify'
  validates :remote, format: { with: /\A[a-zA-Z0-9_-]+\z/ }, if: ->(video){video.remote.present?}
  validate :wrong_video_source
  validate :file_size, if: ->(video){video.source.present?}

  def thumb
    if self.source?
      self.source.thumb
    elsif self.remote?
      "http://img.youtube.com/vi/#{self.remote}/0.jpg"
    else
      'http://brzezia.pl/images/znak-zapytania.png'
    end
  end

  private

    def wrong_video_source
      unless source.blank? ^ remote.blank?
        errors.add(:source, 'must be specify corectly')
      end
    end

    def file_size
      if source.file.size.to_f/(1000*1000) > 100
        errors.add(:source, "You cannot upload a file greater than 100MB")
      end
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, except: [:index, :new, :create]

  def index 
    allow = ['created_at', 'score', 'views']

    @videos = Video.all
    
    @videos = @videos.where(kind: params[:type]) if params[:type]
    @videos = @videos.tagged_with(params[:tag]) if params[:tag]
    @videos = @videos.order("#{params[:sort]} DESC") if allow.include?(params[:sort])
    @videos = Video.where("title LIKE ?", "%#{params[:search]}%") if params[:search]
    @videos = @videos.page(params[:page])

    @params = params.slice(:type, :sort, :tag) # prevent XSS attack
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    @video.remote.sub!(/.*watch\?v=/, '') if @video.remote?
    @video.user = current_user
    @video.tag_list = params[:tag_list]
    if @video.save
      redirect_to video_path(@video), notice: t('videos.notice')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @video.update(video_params)
      @video.tag_list = params[:tag_list]
      @video.save
      redirect_to video_path(@video)
    else
      redirect_to edit_video_path(@video)
    end
  end

  def destroy
    @video.destroy
    redirect_to videos_path
  end

  def show
    @video.increment!(:views)
    if Rating.exists?(user: current_user, video: @video)
      @rate = Rating.find_by(user: current_user, video: @video).score
    else
      @rate = 0
    end
    @comments = @video.comments
    @comment = Comment.new
  end

  def tags
    render json: @video.tag_list.to_json
  end

  def vote
    rate = Rating.find_or_initialize_by(user: current_user, 
                                        video: @video)
    rate.update(score: video_params[:rate])

    avg_score = Rating.where(video: @video).average(:score)
    @video.update(score: avg_score)
    render nothing: true
  end

  def add_comment
    @video.comments.create(comment: params[:comment][:comment], 
                              user: current_user)
    render nothing: true
  end

  private

    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:title, :description, :source, :remote, :kind, :rate)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.haml
.col-md-8.col-md-offset-2
  - if @video.errors.any?
    %ul.alert.alert-danger
      Please review the problems below:
      - @video.errors.full_messages.each do |msg|
        %li.listing-errors= msg

  = simple_form_for @video do |f|
    .inputs
      = f.input :title, label: false, placeholder: 'Title'
      = f.input :description, label: false, placeholder: 'Description', as: :text, input_html: {rows: 4}
      = f.input :tag_list, label: false, placeholder: 'Tags', input_html: { class: 'tm-input' }
      = f.input :kind, collection: [['Tricks', 1], ['Presentation', 2]], label: false, include_blank: false
      .tab-panel
        %ul.nav.nav-tabs{role: 'tablist'}
          %li.active{role: 'presentation'}
            %a{href: '#local', "aria-controls": "local", role: "tab", "data-toggle": "tab"}= t('videos.local_file') + " (*.mp4)"
          %li{role: 'presentation'}
            %a{href: '#remote', "aria-controls": "remote", role: "tab", "data-toggle": "tab"} Youtube
        .tab-content
          .tab-pane.content-tab.active{role: 'tabpannel', id: 'local'}
            = f.file_field :source, accept: 'video/mp4'
          .tab-pane.content-tab{role: 'tabpannel', id: 'remote'}
            = f.input :remote, label: false, placeholder: 'Youtube'
      = f.button :submit, class: "center-block"

app/views/videos/_video.html.haml
.video-thumb.col-md-4
  .thumb
    .text-center
      = link_to video_path(video.id) do
        = image_tag video.thumb, width: 192
        .thumb-title
          = video.title.mb_chars.upcase

app/views/videos/edit.html.haml
%h1.text-center Edytuj filmik
= render 'form'

app/views/videos/index.html.haml
.voffset
  .col-md-3
    .sidebar
      .text-center
        %h2.type{"data-type": params[:type]}= t('.type')       
        .btn-group
          = link_to t('.tricks'), @params.merge(type: 1), class: 'btn btn-default active', id: '1'
          = link_to t('.presentation'), @params.merge(type: 2), class: 'btn btn-default', id: '2'
        %h2.sort{"data-sort": params[:sort]}= t('.sort')
        .btn-group
          = link_to t('.date'), @params.merge(sort: "created_at"), id: 'created_at', class: 'btn btn-default active'
          = link_to t('.rate'), @params.merge(sort: "score"), id: 'score', class: 'btn btn-default'
          = link_to t('.views'), @params.merge(sort: "views"), id: 'views', class: 'btn btn-default'
      .tags
        %h2.text-center.tagg{"data-tag": params[:tag]}= t('.tags')
        .text-center
          - ActsAsTaggableOn::Tag.most_used(20).each do |tag|
            = link_to tag.name, @params.merge(tag: tag.name), class: 'tag', id: "#{tag.name}-tag"
  .col-md-8
    = render @videos
    .row
      .col-md-12
        .text-center
          .pagination
            = paginate @videos

app/views/videos/new.html.haml
%h1.text-center Dodaj nowy filmik
= render 'form'

app/views/videos/show.html.haml
.col-md-8.col-md-offset-2
  .owner-panel.text-center
    - if can? :update, @video
      = link_to edit_video_path(@video) do
        %i.fa.fa-edit
      = link_to @video, method: :delete, data: { confirm: "Are you sure" } do
        %i.fa.fa-trash-o
  .text-center.video-title 
    = @video.title
.text-center
  - if @video.source?
    = video_tag @video.source_url.to_s, width: 640, controls: true, autobuffer: true, class: "red-border"
  - if @video.remote?
    .col-md-6.col-md-offset-3
      .videoWrapper
        %iframe{allowfullscreen: "", frameborder: "0", height: "315", src: "https://www.youtube.com/embed/" + @video.remote, width: "560", class: "red-border"}
%br
.row
  .col-md-2.col-md-offset-3.text-center
    %i.fa.fa-upload.fa-lg
    %br
    = @video.user.login
  .col-md-2.text-center
    %i.fa.fa-eye.fa-lg
    %br
    = @video.views
  .col-md-2.text-center
    #score
      - unless user_signed_in?
        %i.fa.fa-star.fa-lg
        %br
      = @video.score.round(1)
    - if user_signed_in?
      #rate{:rated => @rate}
        .rating
          %span{"data-score" => "5"} ☆
          %span{"data-score" => "4"} ☆
          %span{"data-score" => "3"} ☆
          %span{"data-score" => "2"} ☆
          %span{"data-score" => "1"} ☆
.row
  .col-md-6.col-md-offset-3
    %h5.tags-line
      - @video.tags.each do |tag|      
        = link_to tag.name, videos_path(tag: tag.name), class: 'tag'        
- if @video.description?
  %p.col-md-6.col-md-offset-3.video-description.well
    = @video.description

.row
  .col-md-6.col-md-offset-3
    #comments
      - if @video.comments.exists?
        - @comments.each do |comment|
          - if comment.user == current_user
            = link_to comment, method: :delete, remote: true, class: 'comment-delete' do
              %i.fa.fa-times-circle-o
          .comment
            .comment-author
              = comment.user.login
            .pull-right
              = l comment.created_at
            .comment-body
              = comment.comment
          %br
- if user_signed_in?
  .row
    .col-md-6.col-md-offset-3      
      = simple_form_for @comment, url: add_comment_video_path, remote: true do |v|
        = v.input :comment, as: :text, label: t('.new_comment')
        = v.button :submit, value: t('.comment'), id: 'comment-button'