config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:session, :password, :registration], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "(:locale)", locale: /en|pl/ do
    devise_for :users, skip: [:omniauth_callbacks]
    ActiveAdmin.routes(self)
    get 'search' => 'videos#index', as: :search

    root 'home#index'

    get 'set_language/en', as: :en
    get 'set_language/pl', as: :pl

    scope '/lighter' do
      get '/construction' => 'lighter#construction', as: :construction
      get '/types' => 'lighter#types', as: :types
      get '/history' => 'lighter#history', as: :history
    end

    resources :tutorials
    resources :entries
    resources :images
    resources :comments

    resources :videos do
      member do
        post :vote
        post :add_comment
        get :tags
      end
    end
  end
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  mount_uploader :video, TutorialUploader
  validates :title, :level, :video, presence: true
  validates_numericality_of :level, less_than_or_equal_to: 5, greater_than: 0

  scope :level, ->(level) { where(level: level) }
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def new
    @tutorial = Tutorial.new
  end

  def show
    @tutorial = Tutorial.find(params[:id])
  end

  def create
    @tutorial = Tutorial.new(tutorial_params)
    if @tutorial.save
      redirect_to tutorials_path, notice: 'Tutorial was succesfully created'
    else
      redirect_to new_tutorial_path, notice: 'Unfortunately action failed'
    end
  end

  private

    def tutorial_params
      params.require(:tutorial).permit(:title, :video, :level)
    end
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/_accordion.html.haml
#accordion.panel-group{role: 'tablist', "aria-multiselectable": false}
  .panel.panel-default
    - (1..5).each do |i|
      %div{id: "heading" + i.to_s, class: 'panel-heading', role: 'tab'}     
        %h4.panel-title.text-center
          %a{"data-toggle": "collapse", "data-parent": "#accordion", href: "#level" + i.to_s, "aria-controls": "level" + i.to_s}= t('tutorials.level') + " #{i}"
      %div{id: "level" + i.to_s, class: "panel-collapse collapse #{'in' if i == 1}", role: "tabpanel", "aria-labelledby": "heading" + i.to_s}
        .listGroup
          - Tutorial.level(i).each do |tutorial|
            = link_to tutorial.title, tutorial_path(tutorial), class: "list-group-item text-center"

app/views/tutorials/index.html.haml
.row
  .col-md-3.col-md-offset-1
    = render 'accordion'
  .col-md-7.tuto
    .jumbotron.text-center
      %h1= t('.title')
      %p= t('.paragraph')

app/views/tutorials/new.html.haml
.col-md-6.col-md-offset-3
  = simple_form_for @tutorial do |f|
    = f.input :title, label: false, placeholder: 'Title'
    .col-md-6
      = f.input :level, collection: 1..5
    .col-md-6
      = f.input :video, label: 'Source'    
    .col-md-12.text-center
      = f.button :submit

app/views/tutorials/show.html.haml
.row
  .col-md-3.col-md-offset-1
    = render 'accordion'
  .col-md-7.tuto
    .text-center
      %h2= @tutorial.title
      %br
      = video_tag @tutorial.video_url.to_s, controls: true
      