config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:session, :password, :registration], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "(:locale)", locale: /en|pl/ do
    devise_for :users, skip: [:omniauth_callbacks]
    ActiveAdmin.routes(self)
    get 'search' => 'videos#index', as: :search

    root 'home#index'

    get 'set_language/en', as: :en
    get 'set_language/pl', as: :pl

    scope '/lighter' do
      get '/construction' => 'lighter#construction', as: :construction
      get '/types' => 'lighter#types', as: :types
      get '/history' => 'lighter#history', as: :history
    end

    resources :tutorials
    resources :entries
    resources :images
    resources :comments

    resources :videos do
      member do
        post :vote
        post :add_comment
        get :tags
      end
    end
  end
end

app/views/layouts/_login_modal.haml
#login.modal.fade{:role => "dialog", :tabindex => "-1", "aria-labelledby" => "mySmallModalLabel", "aria-hidden" => "true"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal"} ×
        %h3.text-center= t('basic.login')
      .modal-body
        - if alert
          %p.alert.alert-danger= alert
        = simple_form_for(:user, :url => user_session_path) do |f|
          .inputs
            = f.input :login, required: false, input_html: { id: 'login_field' }
            = f.input :password, required: false
            = f.input :remember_me, as: :boolean if devise_mapping.rememberable?
            = f.button :submit, t('basic.sing_in'), class: 'btn btn-lg btn-success center-block'
        %br
        .text-center          
          = button_to t('basic.sing_in_with_fb'), user_omniauth_authorize_path(:facebook), class: 'btn btn-primary'

app/views/layouts/_registration_modal.haml
#registration.modal.fade{:role => "dialog", :tabindex => "-1", "aria-labelledby" => "mySmallModalLabel", "aria-hidden" => "true"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal"} ×
        %h3.text-center= t('basic.registration')
      .modal-body
        - if alert
          %p.alert.alert-danger= alert
        = simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
          = f.error_notification
          .inputs
            = f.input :email, autofocus: true, input_html: { id: 'reg_field' }
            = f.input :password
            = f.input :password_confirmation
            = f.button :submit, t('basic.sing_up'), class: 'btn btn-success btn-lg center-block'

app/views/layouts/application.haml
!!!
%html{lang: I18n.locale}
  %head
    %meta{charset: "utf-8"}
    %title Lighter.pl
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", rel: "stylesheet"}
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-inverse.navbar-static-top{:role=>"navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Rozwiń nawigacje
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to root_path, class: 'navbar-brand' do
            %i.fa.fa-fire.fa-fw.fa-lg.red-icon
            %b Lighter.pl
        .collapse.navbar-collapse{:id => "bs-example-navbar-collapse-1"}
          %ul.nav.navbar-nav
            %li
              = link_to t('nav.news'), entries_path
            %li
              = link_to t('nav.videos'), videos_path
            %li
              = link_to t('nav.gallery'), images_path
            %li.dropdown
              = link_to t('nav.lighter'), '#', class: "dropdown-toggle", "data-toggle" => "dropdown"
              %ul.dropdown-menu{:role => "menu"}
                %li
                  = link_to t('nav.build'), construction_path
                %li
                  = link_to t('nav.types'), types_path
                %li
                  = link_to t('nav.history'), history_path
            %li
              = link_to t('nav.tutorials'), tutorials_path
            %li
              %a{href: "#", id: 'search-icon'}
                %i.fa.fa-search
            .navbar-form.navbar-left{ role: 'search', id: 'search-form'}
              = form_for(:search, url: search_path, method: :get) do
                = text_field_tag(:search, nil, class: 'form-control', id: 'search-field')
          - if user_signed_in? && current_user.admin?
            %ul.nav.navbar-nav.navbar-right
              %li
                = link_to "A", admin_dashboard_path, class: 'admin-link'
          %ul.nav.navbar-nav.navbar-right.login
            %li.dropdown
              = link_to I18n.locale.upcase, '#', class: 'dropdown-toggle', "data-toggle" => "dropdown"
              %ul.dropdown-lang.dropdown-menu{role: "menu"}
                - other_locales.each do |locale|
                  %li
                    = link_to locale.upcase, send("#{locale}_path")
          - if user_signed_in?
            %ul.nav.navbar-nav.navbar-right
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  - if current_user.avatar?
                    = image_tag current_user.avatar_url, class: 'avatar-frame'
                  - else
                    %i.fa.fa-user
                  = current_user.login
                  %span.caret.red-icon
                %ul.dropdown-menu{:role => "menu"}
                  %li
                    = link_to edit_user_registration_path do
                      %i.fa.fa-cog
                      = t('profil.settings')
                  %li
                    = link_to new_video_path do
                      %i.fa.fa-plus-square
                      = t('profil.add_video')
                  %li
                    = link_to destroy_user_session_path, :method => :delete do
                      %i.fa.fa-sign-out
                      = t('profil.logout')
          - else
            .btn-group.navbar-right
              %a.btn.btn-warning.navbar-btn{:role=>"button", "data-toggle" => "modal", "data-target" => "#registration"}
                = t('basic.sing_up')
              %a.btn.btn-default.navbar-btn{:type => "button", "data-toggle" => "modal", "data-target" => "#login"}
                = t('basic.sing_in')
    .container.main
      = render "layouts/login_modal"
      = render "layouts/registration_modal"
      - flash.each do |key, value|
        %div{class: flash_class(key)}
          = value
      = yield
    .footer
      .container
        .text-center
          copyright © 2016 Michał Olejniczak